# The Nearest Neighbors Algorithm in Python #

No we will try to use the KNN on real music data by rewriting it in python. 
The dataset we will use to start will be the [University of Iowa Musical Instrument Samples Dataset](http://theremin.music.uiowa.edu/index.html). The first two cells in this notebook will load the dataset for you. Make sure you have downloaded the `Iowa_MIS_dataset.mat` file and you have put it the same directory where this notebook lives.

In [1]:
import numpy as np
import scipy.io
from scipy.stats import mode

In [2]:
Iowa_MIS_dataset = scipy.io.loadmat('Iowa_MIS_dataset.mat')
data = Iowa_MIS_dataset['dat_all']

The variable `data` is of size [660,88201], and is is already shuffled (it's always good to double check, just to make sure). The number of rows tells you the number of datapoints in the dataset, and the number of columns - 1 tells you the dimensionality of the dataset. The rightmost column in the matrix contains the labels for all datapoints. Possible labels are:

0 'Bass'

1 'Bassoon'

2 'Cello'

3 'Clarinet'

4 'Flute'

5 'Guitar'

6 'Horn'

7 'Sax'

8 'Trombone'

9 'Trumpet'

10 'Viola'

11 'Violin'

Next, separate the datapoints into training (~80% of the data), validation (~10%), and test sets (~10%) (procedure should be very similar to what you did in Julia).

In [3]:
# general data parameters
N = data.shape[0]
D = data.shape[1]-1
C = 12

np.random.permutation(data)

p_tr, p_vl, p_ts = 0.8, 0.1, 0.1
i_tr = int(np.floor(N*p_tr))
i_vl = i_tr + int(np.floor(N*p_vl))
i_ts = N  #int(np.floor(N*p_ts))
# for i in [p_tr, p_vl, p_ts, i_tr, i_vl, i_ts]:
#     print i
x_tr, x_vl, x_ts = data[:i_tr,:-1], data[i_tr:i_vl,:-1], data[i_vl:i_ts,:-1]
y_tr, y_vl, y_ts = data[:i_tr,-1:], data[i_tr:i_vl,-1:], data[i_vl:i_ts,-1:]

# for i in [data, x_tr, x_vl, x_ts, y_tr, y_vl, y_ts]:
#     print i.shape


(660, 88201)
(528, 88200)
(66, 88200)
(66, 88200)
(528, 1)
(66, 1)
(66, 1)


In [ ]:
max_k = 20
norm = "L1"
for k in xrange(1,max_k,2):
    print "Trying with k = ", k
    num_correct = 0
    for i in xrange(x_vl.shape[0]):

        # calculate the L1 norm between each point that you used to train the model
        # and each point that you use to validate the model.    
        # your code here:
        diffs = np.subtract(x_tr, x_vl[i])
        if norm == "L2":
            diffs = np.square(diffs)
        elif norm == "L1":
            diffs = np.abs(diffs)
        else:
            print "invalid norm"
#         print "diffs ", diffs.shape
        dists = np.sum(diffs, axis=1)
#         print "dists ", dists.shape

        # obtain the indices that would sort the array in ascending order
        # your code here:
        inds = np.argsort(dists)
        k_inds = inds[:k]

        # obtain the labels for the KNNs using their indices
        # your code here:
        labels = y_tr[k_inds]

        # have the neighbors vote [hint: use the scipy function 'mode']
        # your code here:
        predicted_label = mode(labels)
        
        print "Finished classifying validation number: {}, matched with {}, and labeled as {}. Real label was {}".format(i, k_inds, predicted_label, predicted_label.mode[0])

        if  int(predicted_label.mode[0]) == int(y_vl[i]):
            num_correct += 1

    print 'accuracy with ', k, 'nearest neighbors: ', float(num_correct)/x_vl.shape[0]        

Trying with k =  1
[514]
[72]
[514]
[497]
[185]
[514]
[331]
[514]
[331]
[149]
[167]
[94]
[154]
[514]
[514]
[514]
[514]
[384]
[514]
[331]
[514]
[514]
[384]
[514]
[514]
[514]
[514]
[514]
[331]
[514]
[514]
[140]
[331]
[143]
[185]
[119]
[514]
[514]
[514]
[514]
[514]
[514]
[331]
[331]
[331]
[514]
[331]
[514]
[514]
[331]
[280]
[514]
[113]
[514]
[514]
[331]
[514]
[514]
[514]
[514]
[514]
[331]
[331]
[178]
[4]
[514]
accuracy with  1 nearest neighbors:  0.151515151515
Trying with k =  3
[514 384 185]
[ 72 384 514]
[514 384 185]
[497 514 331]
[185 331  67]
[514 384 417]
[331  67   4]
[514 384 417]
[331 384 140]
[149 130 331]
[167 222 308]
[ 94 505 331]
[154 480 309]
[514 384 417]
[514 384 185]
[514 384 143]
[514 384 143]
[384 514 143]
[514 384 417]
[331 514 384]
[514 384 185]
[514 384 143]
[384 514 331]
[514 384 417]
[514 384 417]
[514 384 417]
[514 384 417]
[514 384 417]
[331 514  67]
[514 384 236]
[514 384 474]
[140 113  67]
[331 280 236]
[143 483 514]
[185 514 384]
[331  67   4 384 514 140 143

[331 514  67 384 143   4 333 417 236 527 501 185 140  31 308 413 496]
[514 384 417 185 143   4  67 392 331 358  90 236 140 501 474 113 496]
[514 331 143 417 140 384  67 501  90 185 308   4 413 236 392 358 333]
[331 514 143 384 417  67 140   4 392 236  90 185 413 308 241 333 358]
[280 331  67 185 384 514 140 143   4 308 236 417 496 501 333   7 490]
[514 384 417   4 185 143 474 501 113 358 260  90 222 142 331 258 490]
[113 514 331 384 143  67 185 417 140   4 308 501 236 392 490 413  90]
[514 384 417 185 474   4 143 113 358  90 260 222 142 501 522 258 123]
[514 384 417 185 143 358   4 474  90 113 392 260 501   7 331 496 142]
[331 384  67 185 236 514 140  41 496   4 123 113 501 333 490   7 308]
[514 384 417 236 496 241 185 143   7 474 358 392  67  65  90   4 142]
[514 384 143 417 331 185   4  67 501 140  90 358 392 236 459 333 474]
[514 384 143 417 185   4 501 331 140 308  67 474 527  90 490 113 358]
[514 384 143 417 331 185   4  67 501  90 140 358 392 236 333 474 459]
[514 384 143 417 474

What is the best accuracy that you obtained? Was it above chance?

How could you make this model better?